# Generated by Django 6.0.3 on 2026-03-25 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('limpiapipas', 'Limpiapipas'), ('details', 'Detalles')], default='limpiapipas', max_length=20),
        ),
    ]
