# Generated by Django 6.0.3 on 2026-03-25 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_data_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
